
### 카테고리별로 최저가 조회
GET http://localhost:8080/api/prices

### 카테고리별로 최저가
GET http://localhost:8080/api/prices/categories/hat

### 모든 카테고리의 상품을 구매할 때 최저가 브랜드 계산
GET http://localhost:8080/api/prices/cheapest-brand

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "새상품",
  "price": 10,
  "brandId": 1,
  "categoryId": 6
}

###
DELETE http://localhost:8080/api/products/{{id}}

###
POST http://localhost:8080/api/brands

###
DELETE http://localhost:8080/api/brands/{{id}}